default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release"
    firebase_app_distribution(
    app: "1:158153819260:android:cea7ce70fe08afdfd5f5f9",
    firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
    testers: "elesawy928@gmail.com",
    release_notes: "new release with firebase distribution"
    
  )
  end
end
